apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: "{{ .Chart.Name }}"
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  resourceNames:
  - "{{ .Chart.Name }}"
  verbs:
  - get