apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: "{{ .Chart.Name }}"
  type: {{ .Values.service.type }}
  ports:
  - name: http
    targetPort: {{ .Values.service.port }}
    port: {{ .Values.server.http.port }}
