name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  
jobs:
  dockerbuild:
    uses: CivicAIPortal/dev-ops/.github/workflows/docker.yml@main
    secrets: inherit
    with: 
      dockerfile: "deployment/docker/Dockerfile"
      harbor_config: "deployment/harbor.config"
  helm:
    uses: CivicAIPortal/dev-ops/.github/workflows/helm.yml@main
    secrets: inherit
    with: 
      buildContext:  "deployment/helm"
      harbor_config: "deployment/helm/harbor.config"
